# Generated by Django 5.2.7 on 2026-01-24 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebRTCCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('audio', 'Audio Call'), ('video', 'Video Call')], default='audio', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ringing', 'Ringing'), ('connecting', 'Connecting'), ('active', 'Active'), ('ended', 'Ended'), ('failed', 'Failed'), ('missed', 'Missed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('room_id', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('call_quality', models.CharField(default='good', max_length=20)),
                ('connection_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ICEConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.TextField()),
                ('sdp_mid', models.CharField(blank=True, max_length=255, null=True)),
                ('sdp_mline_index', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ice_connections', to='webrtc.webrtccall')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('candidate', 'ICE Candidate'), ('hangup', 'Hang Up'), ('ringing', 'Ringing'), ('connected', 'Connected')], max_length=20)),
                ('signal_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_signals', to=settings.AUTH_USER_MODEL)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='webrtc.webrtccall')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('new', 'New'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('failed', 'Failed'), ('closed', 'Closed')], default='new', max_length=20)),
                ('local_sdp', models.TextField(blank=True, null=True)),
                ('remote_sdp', models.TextField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_connections', to='webrtc.webrtccall')),
            ],
            options={
                'unique_together': {('call', 'user')},
            },
        ),
    ]
