# Generated by Django 5.2.7 on 2026-01-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickconnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='ended_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(default='0288F67BE8974C2A', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='id',
            field=models.CharField(default='22356a1d710c45b9ae1a', max_length=50, primary_key=True, serialize=False),
        ),
    ]
